remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "default"

# Site Settings
locale                   : "en-US"
title                    : "Javier Ponce"
subtitle                 : "My Personal Website"
repository: "jpadsc/JavierPonce.github.io"

breadcrumbs: true

plugins:
  - jekyll-include-cache
  - jekyll-titles-from-headings