remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "default"

# Site Settings
locale                   : "en-US"
title                    : "Javier Ponce"
subtitle                 : "My Personal Website"

plugins:
  - jekyll-include-cache
  - jekyll-titles-from-headings

header:
  image: assets/images/Geisel-5-L.jpg